### ISSUE TITLE
Permission denied while receiving from Android when signed as a non-admin user

### ISSUE THREAD

**Issue by btlogy** [LeastAuthority/destiny#192]
**Description**
Destiny on Android failed to receive a file and shows a `Permission denied` error when signed as non-admin user:

**To Reproduce**
1. Signed in a non-admin user
2. Install Destiny if needed
3. Start it and complete de on-boarding steps if needed
4. Click on `Receive`
5. Type any correct code (i.e.: 1-paragraph-athens)
6. See error and details

**Expected behavior**
File transfer in progress

**Logs**
```
E flutter : [ERROR:flutter/runtime/dart_vm_initializer.cc(41)] Unhandled Exception: Exception: Permission denied. Could not write to /storage/emulated/0/Download
E flutter : #0      ReceiveSharedState.defaultErrorHandler (package:destiny/views/shared/receive.dart:182)
E flutter : #1      ReceiveSharedState.receive (package:destiny/views/shared/receive.dart:188)
E flutter : <asynchronous suspension>
E flutter : 
```

App Version: 1.0.1

**Smartphone (please complete the following information):**
 - Device: Android
 - OS Version: 11

**Additional context**
Possible root cause to be looked for in the destination directory `/storage/emulated/0/Download`.
As the `0` is likely the admin user id, and should be the current user id (>=10 for non-admin).

**Comment by donpui** [comment]
Yes, this we have not fixed yet.
